spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  profiles:
    include: KEY

  data:
    redis:
      host: localhost # 배포시 redis로 변경
      port: 6379
